# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: falses
cache: packages
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

jobs:
  include:
  - r: 3.6